name: Build APK and Notify Discord

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt' # Specify the distribution

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Verify APK exists
        run: ls -l app/build/outputs/apk/release/

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk

  notify:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit title
        id: get_commit
        run: echo "title=$(git log -1 --pretty=%s)" >> $GITHUB_ENV

      - name: Notify Discord
        run: |
          if [ "${{ needs.build.result }}" == "success" ]; then
            STATUS="succeeded"
          else
            STATUS="failed"
          fi
          COMMIT_TITLE="${{ env.title }}"
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"Build $STATUS: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\nCommit: $COMMIT_TITLE\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
        if: always()
